### ISSUE TITLE
Can't use extends on template

### ISSUE THREAD

**Issue by amorino** [sunscrapers/django-templated-mail#10]
Using something like {% extends 'base.html' %} returns an empty email.

**Comment by bplociennik** [comment]
Seems that issue still exists. I'm using version `Djoser 2.0.3` and `django-templated-mail 1.1.1`. Result the same - empty mail without title too.

**Base template:**
```
{% block html_body %}
    HEADER
    {% block content %}{% endblock content %}
{% endblock html_body %}
```

**Email template**
```
{% extends 'email/base_email.html' %}

{% block subject %}
Account activation on {{ user.email }} {{ site_name }}
{% endblock subject %}

{% block html_body %}
    {{ block.super }}
    {% block content %}
        MIDDLE
    {% endblock content %}
{% endblock html_body %}
 
```

**Comment by elspanishgeek** [comment]
Hitting the same issue. I replicated the tests in d225ff7 and the e-mail output is empty.

**Comment by AlexisMunera98** [comment]
Does anyone have an example to achieve the extensions in the template? 
I have found that the code in version 1.1.1 is different from the master. I also try to run the code in the master to extend the template but the result is the same.

**Comment by toremato** [comment]
bump
